# Pandas

In [2]:
import pandas as pd

## Loading Data into Pandas

In [3]:
pokemonlist=pd.read_csv("pokemon_data.csv")
print(type(pokemonlist)) #DataFrame
print(pokemonlist)

<class 'pandas.core.frame.DataFrame'>
       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [11]:
df = {'Name': ['John', 'Mary'], 'Age': [25, 30]}
df

{'Name': ['John', 'Mary'], 'Age': [25, 30]}

In [11]:
#For looking at the top or bottom of the data
print(pokemonlist.head(5))
print()
print(pokemonlist.tail(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
795  719              Diancie     Rock  Fairy  50     100      150      100
796  719  DiancieMega Diancie     Rock  Fairy  50     160      110      160
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170
799  721            Volcanion     Fire  Water  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
795      150     50           6       True
796      110    110           6       True
797      130     70           6       True
798      130     80           6       True
799       90     70           6       True

In [20]:
#Reading excel files
df_xlsx=pd.read_excel("pokemon_data.xlsx")
print(df_xlsx)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [22]:
df_tab_seperated=pd.read_csv("pokemon_data.txt",delimiter="\t")
print(df_tab_seperated)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

## Reading Data in Pandas

In [25]:
## Reading Headers
print(pokemonlist.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [30]:
## Read each column
print(pokemonlist["Name"])
print()
print(pokemonlist["Name"][0:5])
print()
print(pokemonlist[["Name","HP","Attack"]])

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

                      Name  HP  Attack
0                Bulbasaur  45      49
1                  Ivysaur  60      62
2                 Venusaur  80      82
3    VenusaurMega Venusaur  80     100
4               Charmander  39      52
..                     ...  ..     ...
795                Diancie  50     100
796    DiancieMega Diancie  50     160
797    HoopaHoopa Confined  80     110
798     HoopaHoopa Unbound  80     160
799              Volcanion  80     110

[800 rows x 3 columns]

In [34]:
## Read each row
print(pokemonlist.iloc[6]) #iloc stand for integerlocation
print()
print(pokemonlist.iloc[6:9])

#                     6
Name          Charizard
Type 1             Fire
Type 2           Flying
HP                   78
Attack               84
Defense              78
Sp. Atk             109
Sp. Def              85
Speed               100
Generation            1
Legendary         False
Name: 6, dtype: object

   #                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
6  6                  Charizard   Fire  Flying  78      84       78      109
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159

   Sp. Def  Speed  Generation  Legendary
6       85    100           1      False
7       85    100           1      False
8      115    100           1      False

In [46]:
##Read a specific location(R,C)
print(pokemonlist.iloc[4,1])
print(pokemonlist.iloc[13][1])

Charmander
Caterpie

In [50]:
#Iterating through rows:-
for index,row in pokemonlist.iterrows():
    print(index,"\n",row,sep="")
    if(index==5):break

0
#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object
1
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object
2
#                    3
Name          Venusaur
Type 1           Grass
Type 2          Poison
HP                  80
Attack              82
Defense             83
Sp. Atk            100
Sp. Def            100
Speed               80
Generation           1
Legendary        False
Name: 2, dtype: object
3
#                                 3
Name          VenusaurMega Venusaur
Type 1                        Grass
Type 2                       Poison
HP                               80
Attack                          100
Defense                         123
Sp. Atk                         122
Sp. Def                         120
Speed                            80
Generation                        1
Legendary                     False
Name: 3, dtype: object
4
#                      4
Name          Charmander
Type 1              Fire
Type 2               NaN
HP                    39
Attack                52
Defense               43
Sp. Atk               60
Sp. Def               50
Speed                 65
Generation             1
Legendary          False
Name: 4, dtype: object
5
#                      5
Name          Charmeleon
Type 1              Fire
Type 2               NaN
HP                    58
Attack                64
Defense               58
Sp. Atk               80
Sp. Def               65
Speed                 80
Generation             1
Legendary          False
Name: 5, dtype: object

In [58]:
for index,row in pokemonlist.iterrows():
    print(index,row["Name"])
    if(index==20):break

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey

In [60]:
pokemonlist.loc[pokemonlist["Type 1"]=="Electric"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
31,26,Raichu,Electric,NaN,60,90,55,90,80,110,1,False
88,81,Magnemite,Electric,Steel,25,35,70,95,55,45,1,False
89,82,Magneton,Electric,Steel,50,60,95,120,70,70,1,False
108,100,Voltorb,Electric,NaN,40,30,50,55,55,100,1,False
109,101,Electrode,Electric,NaN,60,50,70,80,80,140,1,False
134,125,Electabuzz,Electric,NaN,65,83,57,95,85,105,1,False
146,135,Jolteon,Electric,NaN,65,65,60,110,95,130,1,False
157,145,Zapdos,Electric,Flying,90,90,85,125,90,100,1,True
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
193,179,Mareep,Electric,NaN,55,40,40,65,45,35,2,False
194,180,Flaaffy,Electric,NaN,70,55,55,80,60,45,2,False
195,181,Ampharos,Electric,NaN,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False
258,239,Elekid,Electric,NaN,45,63,37,65,55,95,2,False
262,243,Raikou,Electric,NaN,90,85,75,115,100,115,2,True
337,309,Electrike,Electric,NaN,40,45,40,65,40,65,3,False
338,310,Manectric,Electric,NaN,70,75,60,105,60,105,3,False
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False
340,311,Plusle,Electric,NaN,60,50,40,85,75,95,3,False
341,312,Minun,Electric,NaN,60,40,50,75,85,95,3,False
448,403,Shinx,Electric,NaN,45,65,34,40,34,45,4,False
449,404,Luxio,Electric,NaN,60,85,49,60,49,60,4,False
450,405,Luxray,Electric,NaN,80,120,79,95,79,70,4,False
464,417,Pachirisu,Electric,NaN,60,45,70,45,90,95,4,False
513,462,Magnezone,Electric,Steel,70,70,115,130,90,60,4,False
517,466,Electivire,Electric,NaN,75,123,67,95,85,95,4,False
531,479,Rotom,Electric,Ghost,50,50,77,95,77,91,4,False
532,479,RotomHeat Rotom,Electric,Fire,50,65,107,105,107,86,4,False
533,479,RotomWash Rotom,Electric,Water,50,65,107,105,107,86,4,False
534,479,RotomFrost Rotom,Electric,Ice,50,65,107,105,107,86,4,False
535,479,RotomFan Rotom,Electric,Flying,50,65,107,105,107,86,4,False
536,479,RotomMow Rotom,Electric,Grass,50,65,107,105,107,86,4,False
581,522,Blitzle,Electric,NaN,45,60,32,50,32,76,5,False
582,523,Zebstrika,Electric,NaN,75,100,63,80,63,116,5,False
648,587,Emolga,Electric,Flying,55,75,60,75,60,103,5,False
663,602,Tynamo,Electric,NaN,35,55,40,45,40,60,5,False
664,603,Eelektrik,Electric,NaN,65,85,70,75,70,40,5,False
665,604,Eelektross,Electric,NaN,85,115,80,105,80,50,5,False
704,642,ThundurusIncarnate Forme,Electric,Flying,79,115,70,125,80,111,5,True
705,642,ThundurusTherian Forme,Electric,Flying,79,105,70,145,80,101,5,True
764,694,Helioptile,Electric,Normal,44,38,33,61,43,70,6,False
765,695,Heliolisk,Electric,Normal,62,55,52,109,94,109,6,False
772,702,Dedenne,Electric,Fairy,67,58,57,81,67,101,6,False

## Sorting/Describing Data

In [61]:
pokemonlist.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [62]:
pokemonlist.sort_values("Name")

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [63]:
pokemonlist.sort_values("Name",ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [64]:
pokemonlist.sort_values(["Type 1","Attack"],ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False
422,382,KyogrePrimal Kyogre,Water,NaN,100,150,90,180,160,90,3,True
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False
107,99,Kingler,Water,NaN,55,130,115,50,50,75,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
446,401,Kricketot,Bug,NaN,37,25,41,25,41,25,4,False
733,665,Spewpa,Bug,NaN,45,22,60,27,30,29,6,False
14,11,Metapod,Bug,NaN,50,20,55,25,25,30,1,False
179,165,Ledyba,Bug,Flying,40,20,30,40,80,55,2,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False

In [65]:
pokemonlist.sort_values(["Type 1","Attack"],ascending=[True,False])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
650,589,Escavalier,Bug,Steel,70,135,105,60,105,20,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
405,370,Luvdisc,Water,NaN,43,30,55,40,65,97,3,False
198,183,Marill,Water,Fairy,70,20,50,20,50,40,2,False
508,458,Mantyke,Water,Flying,45,20,50,60,120,50,4,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False

## Making Changes to the Data

In [66]:
pokemonlist

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [5]:
pokemonlist["Total"]=pokemonlist["HP"]+pokemonlist["Attack"]+pokemonlist["Defense"]+pokemonlist["Sp. Atk"]+pokemonlist["Sp. Def"]+pokemonlist["Speed"]

In [6]:
pokemonlist

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [7]:
45+49+49+65+65+45

318

In [10]:
#deleting a column
pokemonlist=pokemonlist.drop(columns=["Total"])

In [11]:
pokemonlist

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [16]:
#Another way of adding a new column
pokemonlist["Total"]=pokemonlist.iloc[:,4:9].sum(axis=1)
pokemonlist

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,530

In [20]:
#Rearranging columns
pokemonlist_cropped=pokemonlist[["Name","Type 1","Type 2"]]
pokemonlist_cropped

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [31]:
print(pokemonlist.columns)
print(pokemonlist.columns.values)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total'],
      dtype='object')
['#' 'Name' 'Type 1' 'Type 2' 'HP' 'Attack' 'Defense' 'Sp. Atk' 'Sp. Def'
 'Speed' 'Generation' 'Legendary' 'Total']

In [25]:
pokemonlist_cropped=pokemonlist[pokemonlist.columns.values[4:10]]
pokemonlist_cropped

     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0    45      49       49       65       65     45
1    60      62       63       80       80     60
2    80      82       83      100      100     80
3    80     100      123      122      120     80
4    39      52       43       60       50     65
..   ..     ...      ...      ...      ...    ...
795  50     100      150      100      150     50
796  50     160      110      160      110    110
797  80     110       60      150      130     70
798  80     160       60      170      130     80
799  80     110      120      130       90     70

[800 rows x 6 columns]

In [32]:
cols=list(pokemonlist.columns.values)
pokemonlist_cropped=pokemonlist[cols[0:4]+[cols[-1]]+cols[4:-1]]
pokemonlist_cropped

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,273,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,345,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,244,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,550,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,590,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,530,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,530,80,110,120,130,90,70,6,True

In [35]:
#Better than hard coding numbers just in case the data rrangement changes
pokemonlist["Total"]=pokemonlist.iloc[:,cols.index("HP"):cols.index("Speed")].sum(axis=1)
pokemonlist

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,530

## Saving/Exporting our DatatFrame in desired format

In [38]:
pokemonlist.to_csv("modified_pokemon_data.csv") #To save your indexes with your data
pokemonlist.to_csv("modified_pokemon_data.csv", index=False) #To not save your indexes with your data

In [40]:
pokemonlist.to_excel("modified_pokemon_data.xlsx") #To save your indexes with your data
pokemonlist.to_excel("modified_pokemon_data.xlsx",index=False) #To not save your indexes with your data

In [42]:
pokemonlist.to_csv("modified_pokemon_data.txt",sep="\t") #To save your indexes with your data
pokemonlist.to_csv("modified_pokemon_data.txt",index=False,sep="\t") #To not save your indexes with your data

## Filtering Data

In [48]:
df=pokemonlist_cropped
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,273,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,345,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,244,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,550,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,590,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,530,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,530,80,110,120,130,90,70,6,True

In [51]:
df.loc[(df["Type 1"]=='Grass') & (df["Type 2"]=='Dark')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
297,274,Nuzleaf,Grass,Dark,280,70,70,40,60,40,60,3,False
298,275,Shiftry,Grass,Dark,400,90,100,60,90,60,80,3,False
363,332,Cacturne,Grass,Dark,420,70,115,60,115,60,55,3,False

In [52]:
df.loc[(df["Type 1"]=='Grass') | (df["Type 2"]=='Dark')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,273,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,345,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,290,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,658,Greninja,Water,Dark,408,72,95,67,103,71,122,6,False
740,672,Skiddo,Grass,NaN,298,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
743,675,Pangoro,Fighting,Dark,437,95,124,78,69,71,58,6,False
798,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True

In [58]:
new_df=df.loc[((df["Type 1"]=='Grass') | (df["Type 2"]=='Dark')) & (df["HP"] >=80)]
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
77,71,Victreebel,Grass,Poison,420,80,105,65,100,70,70,1,False
111,103,Exeggutor,Grass,Psychic,465,95,95,85,125,65,55,1,False
141,130,GyaradosMega Gyarados,Water,Dark,559,95,155,109,70,130,81,1,False
168,154,Meganium,Grass,NaN,445,80,82,100,83,100,80,2,False
267,248,Tyranitar,Rock,Dark,539,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,629,100,164,150,95,120,71,2,False
298,275,Shiftry,Grass,Dark,400,90,100,60,90,60,80,3,False
390,357,Tropius,Grass,Flying,409,99,68,83,72,87,51,3,False
434,389,Torterra,Grass,Ground,469,95,109,105,75,85,56,4,False
483,435,Skuntank,Poison,Dark,395,103,93,67,71,61,84,4,False
510,460,Abomasnow,Grass,Ice,434,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,564,90,132,105,132,105,30,4,False
516,465,Tangrowth,Grass,NaN,485,100,100,125,110,50,50,4,False
550,492,ShayminLand Forme,Grass,NaN,500,100,100,100,100,100,100,4,True
551,492,ShayminSky Forme,Grass,Flying,473,100,103,75,120,75,127,4,True
613,553,Krookodile,Ground,Dark,427,95,117,80,65,70,92,5,False
652,591,Amoonguss,Grass,Poison,434,114,85,70,85,80,30,5,False
701,640,Virizion,Grass,Fighting,472,91,90,72,90,129,108,5,True
720,652,Chesnaught,Grass,Fighting,466,88,107,122,74,75,64,6,False
741,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
743,675,Pangoro,Fighting,Dark,437,95,124,78,69,71,58,6,False
798,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True

In [59]:
#Resetting the indexes for new_df
new_df=new_df.reset_index()
new_df

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
1,3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
2,77,71,Victreebel,Grass,Poison,420,80,105,65,100,70,70,1,False
3,111,103,Exeggutor,Grass,Psychic,465,95,95,85,125,65,55,1,False
4,141,130,GyaradosMega Gyarados,Water,Dark,559,95,155,109,70,130,81,1,False
5,168,154,Meganium,Grass,NaN,445,80,82,100,83,100,80,2,False
6,267,248,Tyranitar,Rock,Dark,539,100,134,110,95,100,61,2,False
7,268,248,TyranitarMega Tyranitar,Rock,Dark,629,100,164,150,95,120,71,2,False
8,298,275,Shiftry,Grass,Dark,400,90,100,60,90,60,80,3,False
9,390,357,Tropius,Grass,Flying,409,99,68,83,72,87,51,3,False
10,434,389,Torterra,Grass,Ground,469,95,109,105,75,85,56,4,False
11,483,435,Skuntank,Poison,Dark,395,103,93,67,71,61,84,4,False
12,510,460,Abomasnow,Grass,Ice,434,90,92,75,92,85,60,4,False
13,511,460,AbomasnowMega Abomasnow,Grass,Ice,564,90,132,105,132,105,30,4,False
14,516,465,Tangrowth,Grass,NaN,485,100,100,125,110,50,50,4,False
15,550,492,ShayminLand Forme,Grass,NaN,500,100,100,100,100,100,100,4,True
16,551,492,ShayminSky Forme,Grass,Flying,473,100,103,75,120,75,127,4,True
17,613,553,Krookodile,Ground,Dark,427,95,117,80,65,70,92,5,False
18,652,591,Amoonguss,Grass,Poison,434,114,85,70,85,80,30,5,False
19,701,640,Virizion,Grass,Fighting,472,91,90,72,90,129,108,5,True
20,720,652,Chesnaught,Grass,Fighting,466,88,107,122,74,75,64,6,False
21,741,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
22,743,675,Pangoro,Fighting,Dark,437,95,124,78,69,71,58,6,False
23,798,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True

In [76]:
#Resetting the indexes for new_df without keeping the old index column
new_df=df.loc[((df["Type 1"]=='Grass') | (df["Type 2"]=='Dark')) & (df["HP"] >=80)]
new_df=new_df.reset_index(drop=True)
new_df
# #doing it inplace(Conserves some memory)
# new_df=new_df.reset_index(drop=True,inplace=True)
# print(new_df)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
1,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
2,71,Victreebel,Grass,Poison,420,80,105,65,100,70,70,1,False
3,103,Exeggutor,Grass,Psychic,465,95,95,85,125,65,55,1,False
4,130,GyaradosMega Gyarados,Water,Dark,559,95,155,109,70,130,81,1,False
5,154,Meganium,Grass,NaN,445,80,82,100,83,100,80,2,False
6,248,Tyranitar,Rock,Dark,539,100,134,110,95,100,61,2,False
7,248,TyranitarMega Tyranitar,Rock,Dark,629,100,164,150,95,120,71,2,False
8,275,Shiftry,Grass,Dark,400,90,100,60,90,60,80,3,False
9,357,Tropius,Grass,Flying,409,99,68,83,72,87,51,3,False
10,389,Torterra,Grass,Ground,469,95,109,105,75,85,56,4,False
11,435,Skuntank,Poison,Dark,395,103,93,67,71,61,84,4,False
12,460,Abomasnow,Grass,Ice,434,90,92,75,92,85,60,4,False
13,460,AbomasnowMega Abomasnow,Grass,Ice,564,90,132,105,132,105,30,4,False
14,465,Tangrowth,Grass,NaN,485,100,100,125,110,50,50,4,False
15,492,ShayminLand Forme,Grass,NaN,500,100,100,100,100,100,100,4,True
16,492,ShayminSky Forme,Grass,Flying,473,100,103,75,120,75,127,4,True
17,553,Krookodile,Ground,Dark,427,95,117,80,65,70,92,5,False
18,591,Amoonguss,Grass,Poison,434,114,85,70,85,80,30,5,False
19,640,Virizion,Grass,Fighting,472,91,90,72,90,129,108,5,True
20,652,Chesnaught,Grass,Fighting,466,88,107,122,74,75,64,6,False
21,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
22,675,Pangoro,Fighting,Dark,437,95,124,78,69,71,58,6,False
23,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True

In [96]:
#doing it inplace(Conserves some memory)
new_df=df.loc[((df["Type 1"]=='Grass') | (df["Type 2"]=='Dark')) & (df["HP"] >=80)]
new_df.reset_index(drop=True,inplace=True)
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
1,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
2,71,Victreebel,Grass,Poison,420,80,105,65,100,70,70,1,False
3,103,Exeggutor,Grass,Psychic,465,95,95,85,125,65,55,1,False
4,130,GyaradosMega Gyarados,Water,Dark,559,95,155,109,70,130,81,1,False
5,154,Meganium,Grass,NaN,445,80,82,100,83,100,80,2,False
6,248,Tyranitar,Rock,Dark,539,100,134,110,95,100,61,2,False
7,248,TyranitarMega Tyranitar,Rock,Dark,629,100,164,150,95,120,71,2,False
8,275,Shiftry,Grass,Dark,400,90,100,60,90,60,80,3,False
9,357,Tropius,Grass,Flying,409,99,68,83,72,87,51,3,False
10,389,Torterra,Grass,Ground,469,95,109,105,75,85,56,4,False
11,435,Skuntank,Poison,Dark,395,103,93,67,71,61,84,4,False
12,460,Abomasnow,Grass,Ice,434,90,92,75,92,85,60,4,False
13,460,AbomasnowMega Abomasnow,Grass,Ice,564,90,132,105,132,105,30,4,False
14,465,Tangrowth,Grass,NaN,485,100,100,125,110,50,50,4,False
15,492,ShayminLand Forme,Grass,NaN,500,100,100,100,100,100,100,4,True
16,492,ShayminSky Forme,Grass,Flying,473,100,103,75,120,75,127,4,True
17,553,Krookodile,Ground,Dark,427,95,117,80,65,70,92,5,False
18,591,Amoonguss,Grass,Poison,434,114,85,70,85,80,30,5,False
19,640,Virizion,Grass,Fighting,472,91,90,72,90,129,108,5,True
20,652,Chesnaught,Grass,Fighting,466,88,107,122,74,75,64,6,False
21,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
22,675,Pangoro,Fighting,Dark,437,95,124,78,69,71,58,6,False
23,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True

In [99]:
#Pokemons in new_df with names containing 'Mega'
new_df.loc[new_df["Name"].str.contains("Mega")]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
4,130,GyaradosMega Gyarados,Water,Dark,559,95,155,109,70,130,81,1,False
5,154,Meganium,Grass,NaN,445,80,82,100,83,100,80,2,False
7,248,TyranitarMega Tyranitar,Rock,Dark,629,100,164,150,95,120,71,2,False
13,460,AbomasnowMega Abomasnow,Grass,Ice,564,90,132,105,132,105,30,4,False

In [100]:
#Pokemons in new_df with names containing 'Mega'
new_df=df.loc[((df["Type 1"]=='Grass') | (df["Type 2"]=='Dark')) & (df["HP"] >=80)]
new_df.reset_index(drop=True,inplace=True)
new_df.loc[~new_df["Name"].str.contains("Mega")] #Tilde for not

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
2,71,Victreebel,Grass,Poison,420,80,105,65,100,70,70,1,False
3,103,Exeggutor,Grass,Psychic,465,95,95,85,125,65,55,1,False
6,248,Tyranitar,Rock,Dark,539,100,134,110,95,100,61,2,False
8,275,Shiftry,Grass,Dark,400,90,100,60,90,60,80,3,False
9,357,Tropius,Grass,Flying,409,99,68,83,72,87,51,3,False
10,389,Torterra,Grass,Ground,469,95,109,105,75,85,56,4,False
11,435,Skuntank,Poison,Dark,395,103,93,67,71,61,84,4,False
12,460,Abomasnow,Grass,Ice,434,90,92,75,92,85,60,4,False
14,465,Tangrowth,Grass,NaN,485,100,100,125,110,50,50,4,False
15,492,ShayminLand Forme,Grass,NaN,500,100,100,100,100,100,100,4,True
16,492,ShayminSky Forme,Grass,Flying,473,100,103,75,120,75,127,4,True
17,553,Krookodile,Ground,Dark,427,95,117,80,65,70,92,5,False
18,591,Amoonguss,Grass,Poison,434,114,85,70,85,80,30,5,False
19,640,Virizion,Grass,Fighting,472,91,90,72,90,129,108,5,True
20,652,Chesnaught,Grass,Fighting,466,88,107,122,74,75,64,6,False
21,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
22,675,Pangoro,Fighting,Dark,437,95,124,78,69,71,58,6,False
23,720,HoopaHoopa Unbound,Psychic,Dark,600,80,160,60,170,130,80,6,True

In [105]:
#The .str.contains() can also do complicated filtering using regex functions:-
import re
df.loc[df["Type 1"].str.contains("Fire|Grass",regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,273,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,345,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,244,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,297,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,401,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,298,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,530,80,110,120,130,90,70,6,True

In [107]:
df.loc[df["Type 1"].str.contains("fire|grass",regex=True)] #Case matters

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [110]:
df.loc[df["Type 1"].str.contains("fire|grass",flags=re.I,regex=True)] #Regex flag ignorecase

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,273,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,345,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,445,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,545,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,244,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,297,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,401,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,298,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,463,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,530,80,110,120,130,90,70,6,True

In [115]:
df.loc[df["Name"].str.contains("pi[a-z]*",flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,150,45,30,35,20,20,45,1,False
20,16,Pidgey,Normal,Flying,195,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,278,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,378,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,458,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,230,35,55,40,50,50,90,1,False
42,37,Vulpix,Fire,NaN,234,38,41,40,50,65,65,1,False
76,70,Weepinbell,Grass,Poison,335,65,90,50,85,45,55,1,False
84,78,Rapidash,Fire,NaN,395,65,100,70,80,80,105,1,False
136,127,Pinsir,Bug,NaN,415,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,495,65,155,120,65,90,105,1,False
181,167,Spinarak,Bug,Poison,220,40,60,40,40,40,30,2,False
186,172,Pichu,Electric,NaN,145,20,40,15,35,35,60,2,False
189,175,Togepi,Fairy,NaN,225,35,20,65,40,65,20,2,False
202,187,Hoppip,Grass,Flying,200,35,35,40,35,55,50,2,False
219,204,Pineco,Bug,NaN,275,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,400,100,100,80,60,60,50,2,False
266,247,Pupitar,Rock,Ground,359,70,84,70,65,70,51,2,False
345,316,Gulpin,Poison,NaN,262,70,43,53,43,53,40,3,False
357,326,Grumpig,Psychic,NaN,390,80,45,65,90,110,80,3,False
358,327,Spinda,Normal,NaN,300,60,60,60,60,60,60,3,False
359,328,Trapinch,Ground,NaN,280,45,100,45,45,45,10,3,False
390,357,Tropius,Grass,Flying,409,99,68,83,72,87,51,3,False
438,393,Piplup,Water,NaN,274,53,51,53,61,56,40,4,False
463,416,Vespiquen,Bug,Flying,434,70,80,102,80,102,40,4,False
488,440,Happiny,Normal,NaN,190,100,5,5,15,65,30,4,False
490,442,Spiritomb,Ghost,Dark,450,50,92,108,92,108,35,4,False
501,451,Skorupi,Poison,Bug,265,40,50,90,30,55,65,4,False
502,452,Drapion,Poison,Dark,405,70,90,110,60,75,95,4,False
557,498,Tepig,Fire,NaN,263,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,363,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,221,50,55,50,36,30,43,5,False
596,536,Palpitoad,Water,Ground,315,75,65,55,65,55,69,5,False
716,648,MeloettaPirouette Forme,Normal,Fighting,472,100,128,90,77,77,128,5,False
718,650,Chespin,Grass,NaN,275,56,61,65,48,45,38,6,False

In [116]:
df.loc[df["Name"].str.contains("^pi[a-z]*",flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,195,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,278,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,378,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,458,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,230,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,415,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,495,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,145,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,275,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,400,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,274,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,363,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,221,50,55,50,36,30,43,5,False

## Conditional Changes

In [125]:
df.loc[df["Type 1"]=="Fire","Type 1"]="Flamey"
df.loc[df["Type 1"]=="Flamey"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
4,4,Charmander,Flamey,NaN,39,52,43,60,50,65,1,False,244
5,5,Charmeleon,Flamey,NaN,58,64,58,80,65,80,1,False,325
6,6,Charizard,Flamey,Flying,78,84,78,109,85,100,1,False,434
7,6,CharizardMega Charizard X,Flamey,Dragon,78,130,111,130,85,100,1,False,534
8,6,CharizardMega Charizard Y,Flamey,Flying,78,104,78,159,115,100,1,False,534
42,37,Vulpix,Flamey,NaN,38,41,40,50,65,65,1,False,234
43,38,Ninetales,Flamey,NaN,73,76,75,81,100,100,1,False,405
63,58,Growlithe,Flamey,NaN,55,70,45,70,50,60,1,False,290
64,59,Arcanine,Flamey,NaN,90,110,80,100,80,95,1,False,460
83,77,Ponyta,Flamey,NaN,50,85,55,65,65,90,1,False,320
84,78,Rapidash,Flamey,NaN,65,100,70,80,80,105,1,False,395
135,126,Magmar,Flamey,NaN,65,95,57,100,85,93,1,False,402
147,136,Flareon,Flamey,NaN,65,130,60,95,110,65,1,False,460
158,146,Moltres,Flamey,Flying,90,100,90,125,85,90,1,True,490
169,155,Cyndaquil,Flamey,NaN,39,52,43,60,50,65,2,False,244
170,156,Quilava,Flamey,NaN,58,64,58,80,65,80,2,False,325
171,157,Typhlosion,Flamey,NaN,78,84,78,109,85,100,2,False,434
236,218,Slugma,Flamey,NaN,40,40,40,70,40,20,2,False,230
237,219,Magcargo,Flamey,Rock,50,50,120,80,80,30,2,False,380
259,240,Magby,Flamey,NaN,45,75,37,70,55,83,2,False,282
263,244,Entei,Flamey,NaN,115,115,85,90,75,100,2,True,480
270,250,Ho-oh,Flamey,Flying,106,130,90,110,154,90,2,True,590
276,255,Torchic,Flamey,NaN,45,60,40,70,50,45,3,False,265
277,256,Combusken,Flamey,Fighting,60,85,60,85,60,55,3,False,350
278,257,Blaziken,Flamey,Fighting,80,120,70,110,70,80,3,False,450
279,257,BlazikenMega Blaziken,Flamey,Fighting,80,160,80,130,80,100,3,False,530
352,322,Numel,Flamey,Ground,60,60,40,65,45,35,3,False,270
353,323,Camerupt,Flamey,Ground,70,100,70,105,75,40,3,False,420
354,323,CameruptMega Camerupt,Flamey,Ground,70,120,100,145,105,20,3,False,540
355,324,Torkoal,Flamey,NaN,70,85,140,85,70,20,3,False,450
435,390,Chimchar,Flamey,NaN,44,58,44,58,44,61,4,False,248
436,391,Monferno,Flamey,Fighting,64,78,52,78,52,81,4,False,324
437,392,Infernape,Flamey,Fighting,76,104,71,104,71,108,4,False,426
518,467,Magmortar,Flamey,NaN,75,95,67,125,95,83,4,False,457
542,485,Heatran,Flamey,Steel,91,90,106,130,106,77,4,True,523
557,498,Tepig,Flamey,NaN,65,63,45,45,45,45,5,False,263
558,499,Pignite,Flamey,Fighting,90,93,55,70,55,55,5,False,363
559,500,Emboar,Flamey,Fighting,110,123,65,100,65,65,5,False,463
572,513,Pansear,Flamey,NaN,50,53,48,53,48,64,5,False,252
573,514,Simisear,Flamey,NaN,75,98,63,98,63,101,5,False,397
614,554,Darumaka,Flamey,NaN,70,90,45,15,45,50,5,False,265
615,555,DarmanitanStandard Mode,Flamey,NaN,105,140,55,30,55,95,5,False,385
616,555,DarmanitanZen Mode,Flamey,Psychic,105,30,105,140,105,55,5,False,485
692,631,Heatmor,Flamey,NaN,85,97,66,105,66,65,5,False,419
721,653,Fennekin,Flamey,NaN,40,45,40,62,60,60,6,False,247
722,654,Braixen,Flamey,NaN,59,59,58,90,70,73,6,False,336
723,655,Delphox,Flamey,Psychic,75,69,72,114,100,104,6,False,430
730,662,Fletchinder,Flamey,Flying,62,73,55,56,52,84,6,False,298
731,663,Talonflame,Flamey,Flying,78,81,71,74,69,126,6,False,373
735,667,Litleo,Flamey,Normal,62,50,58,73,54,72,6,False,297
736,668,Pyroar,Flamey,Normal,86,68,72,109,66,106,6,False,401
799,721,Volcanion,Flamey,Water,80,110,120,130,90,70,6,True,530

In [126]:
#Changing it back
df.loc[df["Type 1"]=="Flamey","Type 1"]="Fire"
df.loc[df["Type 1"]=="Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,325
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,434
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,534
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,534
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False,234
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False,405
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False,290
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False,460
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False,320
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False,395
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False,402
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False,460
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,490
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False,244
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False,325
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False,434
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False,230
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False,380
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False,282
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,480
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,590
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False,265
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False,350
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False,450
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,530
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False,270
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False,420
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,540
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False,450
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False,248
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False,324
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False,426
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False,457
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True,523
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False,263
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,363
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False,463
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False,252
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False,397
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False,265
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False,385
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False,485
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False,419
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False,247
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False,336
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False,430
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False,298
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False,373
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,297
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,401
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,530

In [129]:
df.loc[df["Total"]>=500,["Generation","Legendary"]]="TEST VALUE"

In [132]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,TEST VALUE,TEST VALUE,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,TEST VALUE,TEST VALUE,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,TEST VALUE,TEST VALUE,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,TEST VALUE,TEST VALUE,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,TEST VALUE,TEST VALUE,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,TEST VALUE,TEST VALUE,530

In [133]:
df.loc[df["Total"]>=500,["Generation","Legendary"]]=["TEST VALUE 1","TEST VALUE 2"]
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,TEST VALUE 1,TEST VALUE 2,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,TEST VALUE 1,TEST VALUE 2,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,TEST VALUE 1,TEST VALUE 2,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,TEST VALUE 1,TEST VALUE 2,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,TEST VALUE 1,TEST VALUE 2,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,TEST VALUE 1,TEST VALUE 2,530

In [4]:
df=pd.read_csv("modified_pokemon_data.csv")
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,550
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,590
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,530
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,600
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,530

## Aggregate Statistics(Group By)

In [151]:
df.groupby("Type 1").mean(numeric_only=True)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000,317.246377
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516,369.580645
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000,467.500000
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909,358.909091
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824,364.588235
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000,350.370370
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154,383.634615
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000,382.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500,375.218750
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857,359.214286
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000,373.593750
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333,370.000000
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408,330.132653
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000,335.571429
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614,394.456140
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909,397.840909
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148,432.444444
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714,364.491071

In [150]:
df.groupby("Type 1").mean(numeric_only=True).sort_values("Defense",ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148,432.444444
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909,397.840909
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000,467.500000
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000,373.593750
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500,375.218750
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714,364.491071
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333,370.000000
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857,359.214286
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000,317.246377
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516,369.580645
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000,335.571429
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154,383.634615
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614,394.456140
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909,358.909091
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000,382.500000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000,350.370370
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824,364.588235
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408,330.132653

In [152]:
df.groupby("Type 1").mean(numeric_only=True).sort_values("Attack",ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000,467.500000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000,350.370370
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000,373.593750
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909,397.840909
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148,432.444444
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516,369.580645
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154,383.634615
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000,382.500000
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000,335.571429
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714,364.491071
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500,375.218750
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408,330.132653
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857,359.214286
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333,370.000000
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614,394.456140
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000,317.246377
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909,358.909091
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824,364.588235

In [153]:
df.groupby("Type 1").sum(numeric_only=True)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,
Bug,23080,3925,4897,4880,3717,4471,4256,222,0,21890
Dark,14302,2071,2740,2177,2314,2155,2361,125,2,11457
Dragon,15180,2666,3588,2764,3099,2843,2657,124,12,14960
Electric,15994,2631,3040,2917,3961,3243,3718,144,4,15792
Fairy,7642,1260,1046,1117,1335,1440,826,70,1,6198
Fighting,9824,1886,2613,1780,1434,1747,1784,91,0,9460
Fire,17025,3635,4408,3524,4627,3755,3871,167,5,19949
Flying,2711,283,315,265,377,290,410,22,2,1530
Ghost,15568,2062,2361,2598,2539,2447,2059,134,2,12007
Grass,24141,4709,5125,4956,5425,4930,4335,235,3,25145
Ground,11401,2361,3064,2715,1807,2008,2045,101,4,11955
Ice,10165,1728,1746,1714,1861,1831,1523,85,2,8880
Normal,31279,7573,7200,5865,5470,6245,7012,299,2,32353
Poison,7050,1883,2091,1927,1692,1803,1780,71,0,9396
Psychic,21706,4026,4073,3858,5609,4918,4645,193,14,22484
Rock,17280,2876,4086,4435,2787,3321,2460,152,4,17505
Steel,11957,1761,2503,3412,1823,2177,1492,104,4,11676
Water,33946,8071,8305,8170,8379,7898,7388,320,4,40823

In [155]:
df.groupby("Type 1").count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112

In [5]:
#if we dont want so many useless rows
df["Count"]=1
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Count
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545,1
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,550,1
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,590,1
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,530,1
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,600,1
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,530,1

In [10]:
print(df.groupby("Type 1").count()["Count"])

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: Count, dtype: int64

In [12]:
df.groupby(["Type 1","Type 2"]).count()["Count"]

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: Count, Length: 136, dtype: int64

## Working with large amounts of Data

In [19]:
new_df=pd.DataFrame(columns=df.columns)
for df in pd.read_csv("modified_pokemon_data.csv",chunksize=5):
    results=df.groupby(["Type 1"]).count()
    new_df=pd.concat([new_df,results])

In [20]:
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Fire,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Grass,4,4,NaN,4,4,4,4,4,4,4,4,4,4
Fire,4,4,NaN,3,4,4,4,4,4,4,4,4,4
Water,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Bug,2,2,NaN,0,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Fairy,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Flying,2,2,NaN,2,2,2,2,2,2,2,2,2,2
Fire,1,1,NaN,1,1,1,1,1,1,1,1,1,1
Psychic,2,2,NaN,2,2,2,2,2,2,2,2,2,2
Rock,2,2,NaN,2,2,2,2,2,2,2,2,2,2